# lts-9.5
resolver: ghc-8.4.1
packages:
- '.'
extra-deps:
- HUnit-1.6.0.0
- QuickCheck-2.12
- ansi-terminal-0.8.0.4
- call-stack-0.1.0
- clock-0.7.2
- colour-2.3.4
- erf-2.0.0.0
- hspec-2.5.6
- hspec-core-2.5.6
- hspec-discover-2.5.6
- hspec-expectations-0.8.2
- primitive-0.6.4.0
- quickcheck-io-0.2.0
- random-1.1
- setenv-0.1.1.3
- tf-random-0.5
